
POST https://localhost:44357/accounts/reset-password/
Content-Type: application/json

{
    "token": "0FFE83355F93F9270F1AE738D3B88D8B050F22892CD00A045E13DDABA44DE1BBFD61DC5ECD4566C8",
     "password": "my-super-secret-password",
     "confirmPassword": "my-super-secret-password"
}